### ISSUE TITLE
Display the new person

### ISSUE THREAD

**Issue by anitaschiller** [anitaschiller/christmas-ideas#2]
## Value Statement
As a customer I want to see a list of the already created persons so that I have an overview of all the people I would like to send a gift to.

## Description
-- Description --

##Complexity
M

## Acceptance Criteria
- User can see all submitted persons on the "home" page
- Members are sorted in an alphabetical order

## Tasks
- [ ] Create Card component
- [ ] Render persons from the corresponding array on the "home" page
- [ ] Sort members in the array should be alphabetical (acc. to first name)
